apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: layer1
spec:
  host: layer1
  subsets:
  - name: v1
    labels:
      version: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: layer2
spec:
  host: layer2
  subsets:
  - name: v1
    labels:
      version: v1