apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: layer2
spec:
  host: layer2
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 1
        http:
          http1MaxPendingRequests: 1
          maxRequestsPerConnection: 1
      outlierDetection:
        baseEjectionTime: 180.000s
        consecutiveErrors: 1
        interval: 1.000s
        maxEjectionPercent: 100   
  - name: v2
    labels:
      version: v2   
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 1
        http:
          http1MaxPendingRequests: 1
          maxRequestsPerConnection: 1
      outlierDetection:
        baseEjectionTime: 180.000s
        consecutiveErrors: 1
        interval: 1.000s
        maxEjectionPercent: 100   
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: layer2
spec:
  hosts:
  - layer2
  http:
  - match:
    - uri:
        prefix: /call-layers
    - uri:
        exact: /get-info        
    - uri:
        exact: /
    route:
    - destination:
        host: layer2
        port:
          number: 8080
        subset: v1
      weight: 50
    - destination:
        host: layer2
        port:
          number: 8080
        subset: v2
      weight: 50
  
